### ISSUE TITLE
Fix Deno --location issue

### ISSUE THREAD

**Issue by bootsa** [InvasionBiologyHypotheses/enKORE-corpus-processor#2]
[postprocess.js](https://github.com/InvasionBiologyHypotheses/enKORE-corpus-processor/blob/main/postprocess.js) fails on execution of the github action with output:

```
Error: Command failed: NO_COLOR=true deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable ./postprocess.js ./corpus/entries.json
Warning Implicitly using latest version (v0.18.3) for https://deno.land/x/sheetjs/types/index.d.ts
Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
error: Uncaught ReferenceError: Access to "location", run again with --location <href>.
  const corsEnabled = typeof location !== 'undefined' && typeof document !== 'undefined';
                      ^
    at get (deno:extensions/web/12_location.js:365:17)
    at dew (https://dev.jspm.io/npm:@citation-js/core@0.5.4/lib/util/fetchFile.dew.js:34:23)
    at dew (https://dev.jspm.io/npm:@citation-js/core@0.5.4/lib/util/index.dew.js:73:20)
    at dew (https://dev.jspm.io/npm:@citation-js/core@0.5.4/lib/index.dew.js:35:38)
    at https://dev.jspm.io/@citation-js/core:2:16
```

Looks like CitationJS is using a relative path to fetch data. As Deno isn't working on a specific url there is no path to provide for the relative url. This can be circumvented by providing a base url using the [location flag](https://deno.land/manual/runtime/location_api#location-flag). As we don't call Deno directly (it is handled by the flat data action) we don't have direct access to adding the flag. Can we pass it in through the Action? Or can we get CitationJS to pass a full URL - e.g. through a configuration parameter?

**Comment by bootsa** [comment]
CitationJS is only querying `location` as a heuristic to determine if it's being run in the browser in this line:

```js
// Browser environments have CORS enabled
const corsEnabled = typeof location !== 'undefined' && typeof document !== 'undefined'
```

https://github.com/citation-js/citation-js/blob/1af82342ea5b216daba0aee492c6b56f57c2c999/packages/core/src/util/fetchFile.js#L8-L9

It looks like Deno misinterprets this as `location` being needed and throw an exception, quitting the process.

There is no standard way to pass in the location flag through the action - however prepending it to the filename field seems to work! https://github.com/InvasionBiologyHypotheses/enKORE-corpus-processor/commit/218c95f26d595b7506c3c3b2417981382d4ef57b  🎉

![image](https://user-images.githubusercontent.com/22413/159956755-65fac7e4-feb7-4022-9118-08565d15b3eb.png)

Now that it is working, will reduce the frequency of the Action to once an hour.
